=== jarronb-iit/itms448-sourcecode-test-DataVison/report.dtd
<!-- Version 1.2 -->
<!-- NOTE: THIS DTD IS ONLY A GUIDE. IT MAY NOT BE CORRECT. -->
<!-- DON'T TRUST IT. -->

<!-- All sizes are in points (72 points == 1 inch) -->

<!-- Color is stored as "red;green;blue;alpha". Each component is an -->
<!-- integer from 0 to 255. -->

<!ELEMENT report	(description, bean-scripting-framework?, formula?,
			 paper, field?, usercols?, source, subreports?,
			 parameters?, formulas?, headers?, footers?, page?,
			 groups?, details)
>
<!ATTLIST report	dtd-version	CDATA	""
			name		CDATA	""
			title		CDATA	""
			author		CDATA	""
>

<!ELEMENT bean-scripting-framework	language*>
<!ATTLIST bean-scripting-framework
			default-language CDATA	#REQUIRED>

<!ELEMENT language EMPTY>
<!ATTLIST language
			name		CDATA	#REQUIRED
			class		CDATA	#REQUIRED
>

<!-- With description, PCDATA is text of report description -->
<!ELEMENT description	(#PCDATA)>

<!-- Default paper orientation is portrait, but I've forgotten how to -->
<!-- specify that in a DTD. -->
<!ELEMENT paper EMPTY>
<!ATTLIST paper		name		CDATA	#REQUIRED
	  orientation	(portrait|landscape) "portrait"
>

<!ELEMENT parameters	(parameter*)>
<!ELEMENT parameter	(default*)>
<!ATTLIST parameter	id		CDATA	#REQUIRED
			type		(boolean
					|string
					|numeric
					|date)	#REQUIRED
			name		CDATA	#REQUIRED
			question	CDATA	#REQUIRED
			arity		(single
					|range
					|list-single
					|list-multiple)	#REQUIRED
>

<!ELEMENT default	(#PCDATA)>

<!ELEMENT formulas	(formula*) >

<!-- With formula, PCDATA is text of formula -->
<!ELEMENT formula	(#PCDATA)>
<!-- If language is not given, it defaults to report's default lanuage -->
<!ATTLIST formula	id		CDATA	#REQUIRED
			name		CDATA	#REQUIRED
			language	CDATA
>

<!ELEMENT usercols	(usercol*) >

<!-- With user-defined columns, PCDATA is text of formula -->
<!ELEMENT usercol	(#PCDATA)>
<!ATTLIST usercol	id		CDATA	#REQUIRED
			name		CDATA	#REQUIRED
>

<!ELEMENT source	(database|charsep) query?>

<!ELEMENT database EMPTY >
<!ATTLIST database	driverClassName	CDATA	#REQUIRED
			connInfo	CDATA	#REQUIRED
			name		CDATA	#REQUIRED
			username	CDATA	#REQUIRED
>

<!-- subreport-joins only appear within a query inside a subreport -->
<!ELEMENT query		(join|where|sort|subreport-joins)*>

<!-- subreport-joins only appear within a query inside a subreport -->
<!ELEMENT subreport-joins	join*>

<!ELEMENT join EMPTY >
<!ATTLIST join		from		CDATA	#REQUIRED
			to		CDATA	#REQUIRED
			relation	CDATA	#REQUIRED
>

<!-- With where clause, PCDATA is text of where clause -->
<!ELEMENT where		(#PCDATA)>

<!ELEMENT sort EMPTY >
<!ATTLIST sort		column		CDATA	#REQUIRED
			order		(ascending|descending)	"ascending"
>

<!ELEMENT charsep	(column*|metadata-url)>
<!ATTLIST charsep	sep-char	CDATA	#IMPLIED
>

<!ELEMENT column EMPTY >
<!ATTLIST column	name		CDATA	#REQUIRED
			type		(string | number | date)
			date-format	CDATA
>

<!-- With metadata-url, PCDATA is the URL from which we read an XML file -->
<!-- describing columns (same as using inline "column" elements). -->
<!-- See metadata.dtd for the format of that file. -->
<!ELEMENT metadata-url	(#PCDATA) >

<!ELEMENT subreports	subreport*>
<!ELEMENT subreport	query details>
<!ATTLIST subreport	id		CDATA	#REQUIRED>

<!ELEMENT page		(headers?,footers?) >

<!ELEMENT headers	(section*) >

<!ELEMENT footers	(section*) >

<!ELEMENT groups	(group*) >

<!ELEMENT group		(headers?, footers?)>
<!-- column is deprecated, replaced by groupable-id and -->
<!--  groupable-type. For now, both will work. -->
<!ATTLIST group		column		CDATA	#REQUIRED
			groupable-id	CDATA	#REQUIRED
			groupable-type	CDATA	#REQUIRED
			sort-order	(asc|desc)
>

<!ELEMENT details	(section*)>

<!ELEMENT section	((field|line)*|suppression-proc?) >
<!ATTLIST section	height		CDATA	#REQUIRED
			pagebreak	(true|false) "false"
>

<!ELEMENT suppression-proc (formula?) >
<!ATTLIST suppression-proc state	(hide|show|proc) #REQUIRED
>

<!ELEMENT field		(bounds|format|border)*>
<!ATTLIST field		type		(column
					|formula
					|parameter
					|text
					|special
					|image
					|sum
					|average
					|count
					|min
					|max
					|stdev)
						#REQUIRED
			value		CDATA	#REQUIRED
>
<!ATTLIST field		visible		(true|false) "true"
>

<!ELEMENT bounds	EMPTY>
<!ATTLIST bounds	x		CDATA	#REQUIRED
			y		CDATA	#REQUIRED
			width		CDATA	#REQUIRED
			height		CDATA	#REQUIRED
>

<!ELEMENT format	EMPTY>
<!ATTLIST format	font		CDATA #IMPLIED
			size		CDATA #IMPLIED
			bold		CDATA #IMPLIED
			italic		CDATA #IMPLIED
			underline	CDATA #IMPLIED
			wrap		CDATA #IMPLIED
			color		CDATA #IMPLIED
			align		(left|right|center) "right"
>

<!-- A border has from one to four edges -->
<!ELEMENT border (edge?,edge?,edge?,edge?) >
<!ATTLIST border	color		CDATA #IMPLIED
>

<!ELEMENT edge		EMPTY>
<!ATTLIST edge		location	(top|left|bottom|right)	#REQUIRED
			style		(line|dot|dash) "line"
			thickness	CDATA #IMPLIED
			number		CDATA #IMPLIED
>

<!ELEMENT line		(point,point) >
<!ATTLIST line		thickness	CDATA #IMPLIED
			color		CDATA #IMPLIED
			visible		(true|false) "true"
>

<!ELEMENT point		EMPTY>
<!ATTLIST point		x		CDATA	#REQUIRED
			y		CDATA	#REQUIRED
>

=== jarronb-iit/itms448-sourcecode-test-DataVison/examples/subreport.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- <!DOCTYPE report SYSTEM "report.dtd"> -->

<!-- This is an example report that can be used as a subreport. Add -->
<!-- it to a report, using a join "office.name &lt;= office.name". -->
<!-- Move the subreport field into a group header section (either -->
<!-- the existing one or a new one that you create under the -->
<!-- existing one). Make it taller so it can fit a few lines of text. -->

<!-- For each group, you will see a list of all office name that are -->
<!-- &gt;= (not &lt;=) the current office name. That's because the left -->
<!-- "office.name" is replaced by the current value of the office name -->
<!-- in the master report. The right office.name is the subreport's -->
<!-- value when its query gets run. -->

<!-- NOTE: this subreport's column names contain a schema name so -->
<!-- it will work with my PostgreSQL setup. To use it with MySQL, -->
<!-- for example, you may have to remove the "public." before each -->
<!-- column name. -->

<report dtd-version="1.2"
	name="subreport" title="Example Subreport" author="Jim Menard">

  <bean-scripting-framework default-language="Ruby">
    <language name="Ruby" class="org.jruby.javasupport.bsf.JRubyEngine"/>
  </bean-scripting-framework>

  <!-- Default orientation is portrait. -->
  <paper name="US-Letter" />

  <!-- Data source. In this case, a database. -->
  <!-- When this is imported as a subreport, the driver info is ignored. -->
  <source>

    <database driverClassName="com.mysql.jdbc.Driver"
	connInfo="jdbc:mysql://localhost/dv_example"
	name="dv_example" username="jimm" />

    <query>
      <sort order="ascending" column="public.office.name" />
    </query>

  </source>

  <details>
    <section height="20">
      <field id="11" type="column" value="public.office.name">
	<bounds x="10" y="0" width="80" height="20" />
	<format align="right" />
      </field>
    </section>
  </details>

</report>

=== jarronb-iit/itms448-sourcecode-test-DataVison/jimm/datavision/test/data/charsep.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- This file can read the data file charsep_data.csv -->

<!-- <!DOCTYPE report SYSTEM "report.dtd"> -->

<!-- All sizes are in points (72 points == 1 inch). -->

<!-- All coordinates and lengths are floating point, but may be truncated -->
<!-- by layout engines. -->

<!-- Colors are stored as "red;green;blue;alpha". Each component is an -->
<!-- integer from 0 to 255. -->

<!-- You will have to edit the image URL below. Search for "file:" -->

<report dtd-version="1.2"
	name="example1" title="Example Report" author="Jim Menard">

  <description><![CDATA[]]></description>

  <bean-scripting-framework default-language="Ruby">
    <language name="Ruby" class="org.jruby.javasupport.bsf.JRubyEngine"/>
  </bean-scripting-framework>

  <!-- Default orientation is portrait. -->
  <paper name="US-Letter" />

  <!-- Data source. In this case, a comma-separated file. This -->
  <!-- definition describes the file charsep_data.csv -->
  
  <source>

    <!-- The column names happen to be the same as database table.column -->
    <!-- names, but that's just a coincidence. OK, I'm lazy. -->
    <charsep sep-char=",">
      <!-- We need to define column names and types. For date columns, -->
      <!-- we need to define a string that will be used to parse the -->
      <!-- string so we can turn it into a java.lang.Date object -->
      <!-- Actually, you ccould skip the date-format string; the default -->
      <!-- parse string (yyyy-MM-dd) is the same string. -->
      <column name="office.name" type="string" />
      <column name="jobs.ID" type="number" />
      <column name="jobs.title" type="string" />
      <column name="jobs.hourly rate" type="number" />
      <column name="jobs.post_date" type="date" date-format="yyyy-MM-dd" />
    </charsep>

    <query>
      <where><![CDATA[{office.name} != 'Chicago']]></where>
    </query>

  </source>

  <formulas>
  <!-- Use Ruby for formula definitions. -->
  <!-- {jobs.ID} means database column jobs.ID -->
  <!-- {@1} means formula with id "1" -->
  <!-- {%report.title} means calculated value "report.title" -->

    <!-- The first formula checks for nil hourly rate. If so, it -->
    <!-- returns nil (which will become an empty NULL value). -->
    <formula id="1" name="hourly rate / 100"><![CDATA[{jobs.hourly rate}.nil? ? nil : {jobs.hourly rate} / 100.0]]></formula>
    <formula id="2" name="refs f1"><![CDATA[{@1}]]></formula>
  </formulas>

  <usercols>
    <usercol id="1" name="Short Title"><![CDATA[substr(jobs.title, 1, 8)]]></usercol>
  </usercols>

  <headers>
    <section height="42">
      <field id="15" type="image" value="file:examples/Home16.gif">
	<bounds x="8" y="8" width="16" height="16" />
      </field>
      <field id="1" type="special" value="report.title">
	<bounds x="100" y="0" width="397" height="28" />
	<format size="24" align="center" bold="true"
	    name="Helvetica" color="0;0;255;255" />
	<border>
	  <edge location="bottom" number="2" />
	  <edge location="top" number="2" />
	  <edge location="left" number="2" />
	  <edge location="right" number="2" />
	</border>
      </field>
      <field id="2" type="special" value="report.date">
	<bounds x="100" y="28" width="397" height="14" />
	<format align="center" name="Helvetica" color="0;0;255;127"
	 format="yyyy-MM-dd" />
      </field>
    </section>
  </headers>

  <footers>
    <section height="30">
      <field id="16" type="text">
	<text><![CDATA[Grand Total:]]></text>
	<bounds x="250" y="8" width="150" height="20" />
	<format align="right" size="14" bold="true" />
	<border>
	  <edge location="top" />
	</border>
      </field>
      <field id="17" type="sum" value="13"><!-- formula in field 13 -->
	<bounds x="400" y="8" width="100" height="20" />
	<format align="right" size="14" bold="true" format="$#,###.00" />
	<border>
	  <edge location="top" />
	</border>
      </field>
      <field id="21" type="special" value="report.row">
	<bounds x="500" y="8" width="20" height="20" />
      </field>
      <field id="26" type="special" value="group.count">
	<bounds x="530" y="8" width="20" height="20" />
      </field>
    </section>
  </footers>

  <page>

    <!-- page headers -->
    <headers>
      <section height="30">
	<field id="3" type="text">
	  <text><![CDATA[Job #]]></text>
	  <bounds x="10" y="0" width="40" height="20" />
	  <format align="right" bold="true" underline="true" />
	</field>
	<field id="4" type="text">
	  <text><![CDATA[Title]]></text>
	  <bounds x="70" y="0" width="320" height="20" />
	  <format align="left" bold="true" underline="true" />
	</field>
	<field id="5" type="text">
	  <text><![CDATA[Hourly Rate]]></text>
	  <bounds x="400" y="0" width="100" height="20" />
	  <format align="right" bold="true" underline="true" />
	</field>
      </section>
    </headers>

    <!-- page footers -->
    <footers>
      <section height="50">
	<field id="6" type="special" value="page.number">
	  <bounds x="475" y="0" width="90" height="20" />
	  <format align="right" italic="true" format="Page 0" />
	  <border>
	    <edge location="top" number="2"/>
	  </border>
	</field>
      </section>
    </footers>

  </page>

  <!-- group -->
  <groups>
  <group groupable-id="office.name" groupable-type="column">
    <headers>
      <section height="30">
	<field id="7" type="column" value="office.name">
	  <bounds x="0" y="0" width="250" height="20" />
	  <format align="left" size="14" bold="true" underline="true" />
	</field>
      </section>
    </headers>
    <footers>
      <section height="30">
	<field id="8" type="text">
	  <text><![CDATA[Total:]]></text>
	  <bounds x="340" y="8" width="60" height="20" />
	  <format align="right" size="14" bold="true" />
	  <border>
	    <edge location="top" />
	  </border>
	</field>
	<field id="9" type="sum" value="13"><!-- formula in field 13 -->
	  <bounds x="400" y="8" width="100" height="20" />
	  <format align="right" size="14" bold="true" format="$#,###.00" />
	  <border>
	    <edge location="top" />
	  </border>
	</field>
	<field id="22" type="special" value="report.row">
	  <bounds x="500" y="8" width="20" height="20" />
	</field>
	<field id="27" type="special" value="group.count">
	  <bounds x="520" y="8" width="20" height="20" />
	</field>
      </section>
    </footers>
  </group>
  <group column="jobs.post_date">
    <headers>
      <section height="30">
	<field id="18" type="column" value="jobs.post_date">
	  <bounds x="0" y="0" width="250" height="20" />
	  <format align="left" size="12" bold="true" underline="false" format="yyyy-MM-dd" />
	</field>
      </section>
    </headers>
    <footers>
      <section height="30">
	<field id="19" type="text">
	  <text><![CDATA[Post Date Total:]]></text>
	  <bounds x="250" y="8" width="150" height="20" />
	  <format align="right" size="14" bold="true" />
	  <border>
	    <edge location="top" />
	  </border>
	</field>
	<field id="20" type="sum" value="13"><!-- formula in field 13 -->
	  <bounds x="400" y="8" width="100" height="20" />
	  <format align="right" size="14" bold="true" format="$#,###.00" />
	  <border>
	    <edge location="top" />
	  </border>
	</field>
	<field id="23" type="special" value="report.row">
	  <bounds x="500" y="8" width="20" height="20" />
	</field>
	<field id="28" type="special" value="group.count">
	  <bounds x="520" y="8" width="20" height="20" />
	</field>
      </section>
    </footers>
  </group>
  </groups>

  <!-- details -->
  <details>
    <section height="20">
      <field id="10" type="column" value="jobs.ID">
	<bounds x="10" y="0" width="40" height="20" />
	<format align="right" />
      </field>
      <field id="11" type="column" value="jobs.title">
	<bounds x="70" y="0" width="275" height="20" />
	<!-- Set wrap to false because tests are simple and assume -->
	<!-- entire title is on one line. -->
	<format align="left" wrap="false" />
	<border>
	  <edge location="right" />
	</border>
      </field>
      <field id="12" type="column" value="jobs.hourly rate">
	<bounds x="350" y="0" width="50" height="20" />
	<format align="right" />
      </field>
      <field id="13" type="formula" value="1">
	<bounds x="400" y="0" width="100" height="20" />
	<format align="right" format="$#,###.00"/>
      </field>
      <field id="14" type="formula" value="2">
	<bounds x="500" y="0" width="75" height="20" />
	<format align="right" format="#,###.##"/>
      </field>
      <field id="24" type="special" value="report.row">
	<bounds x="510" y="8" width="20" height="20" />
      </field>
      <field id="26" type="special" value="group.count">
	<bounds x="520" y="8" width="20" height="20" />
      </field>
    </section>
  </details>

</report>

=== jarronb-iit/itms448-sourcecode-test-DataVison/jimm/datavision/test/data/test.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- <!DOCTYPE report SYSTEM "report.dtd"> -->

<!-- All sizes are in points (72 points == 1 inch) -->

<report dtd-version="1.2"
	name="example1" title="Example Report" author="Jim Menard">

  <description><![CDATA[]]></description>

  <bean-scripting-framework default-language="Ruby">
    <language name="Ruby" class="org.jruby.javasupport.bsf.JRubyEngine"/>
  </bean-scripting-framework>

  <paper name="US-Letter" />

  <usercols>
    <usercol id="1" name="Short Title"><![CDATA[substr(jobs.title, 1, 8)]]></usercol>
    <usercol id="2" name="Short Office Name"><![CDATA[substr(office.name, 1, 5)]]></usercol>
  </usercols>

  <source>
    <database driverClassName="org.postgresql.Driver"
	connInfo="jdbc:postgresql:dv_example"
	name="public" username="jimm" />

    <query>
      <join from="jobs.fk_office_id" to="office.id" relation="=" />
      <sort order="ascending" column="jobs.ID" />
      <sort order="asc" groupable-id="1" groupable-type="usercol"/>
      <where><![CDATA[{jobs.ID} < 100]]></where>
    </query>
  </source>

  <parameters>
    <parameter id="1" type="string" name="String Param"
      question="What string do you like?" arity="single">
      <default><![CDATA[Chicago]]></default>
    </parameter>
    <parameter id="2" type="numeric" name="Number Range"
      question="Roughly how old are you?" arity="range">
      <default><![CDATA[10]]></default>
      <default><![CDATA[120]]></default>
    </parameter>
    <parameter id="3" type="numeric" name="Number List"
      question="Pick a number, any number." arity="list-single">
      <default><![CDATA[1.2]]></default>
      <default><![CDATA[3.4]]></default>
      <default><![CDATA[]]></default>
    </parameter>
    <parameter id="4" type="numeric" name="Pick One"
      question="Pick as many numbers as you like." arity="list-multiple">
      <default><![CDATA[1]]></default>
      <default><![CDATA[2]]></default>
      <default><![CDATA[3]]></default>
      <default><![CDATA[4]]></default>
      <default><![CDATA[5]]></default>
      <default><![CDATA[6]]></default>
      <default><![CDATA[7]]></default>
      <default><![CDATA[8]]></default>
      <default><![CDATA[9]]></default>
      <default><![CDATA[10]]></default>
    </parameter>
    <parameter id="5" type="boolean" name="Yes/No"
      question="Do you breathe regularly?" arity="single">
      <default>yes</default>
    </parameter>
    <parameter id="6" type="date" name="Date"
      question="When did you last take a shower?" arity="single">
    </parameter>
  </parameters>

  <formulas>
  <!-- Use Ruby for formula definitions. -->
  <!-- {jobs.ID} means database column jobs.ID -->
  <!-- {@1} means formula with id "1" -->
  <!-- {%report.title} means calculated value "report.title" -->

    <!-- The first formula checks for nil hourly rate. If so, it -->
    <!-- returns nil (which will become an empty NULL value). -->
    <formula id="1" name="hourly rate / 100"><![CDATA[{jobs.hourly rate}.nil? ? nil : {jobs.hourly rate} / 100.0]]></formula>
    <formula id="2" name="refs f1"><![CDATA[{@1}]]></formula>
    <formula id="3" name="contains usercol"><![CDATA[{!1}]]></formula>
  </formulas>

  <headers>
    <section height="42">
      <field id="15" type="parameter" value="1">
	<bounds x="20" y="0" width="50" height="12" />
      </field>
      <field id="1" type="special" value="report.title">
	<bounds x="100" y="0" width="397" height="28" />
	<format size="24" align="center" bold="true"
	    name="Helvetica" color="0;0;255;255" />
	<border>
	  <edge location="bottom" number="2" />
	  <edge location="top" number="2" />
	  <edge location="left" number="2" />
	  <edge location="right" number="2" />
	</border>
      </field>
      <field id="2" type="special" value="report.date">
	<bounds x="100" y="28" width="397" height="14" />
	<format align="center" name="Helvetica" color="0;0;255;127"
	 format="yyyy-MM-dd" />
      </field>
    </section>
  </headers>

  <footers>
    <section height="30">
      <field id="16" type="text">
	<text><![CDATA[Grand Total:]]></text>
	<bounds x="250" y="8" width="150" height="20" />
	<format align="right" size="14" bold="true" />
	<border>
	  <edge location="top" />
	</border>
      </field>
      <field id="17" type="sum" value="13"><!-- formula in field 13 -->
	<bounds x="400" y="8" width="100" height="20" />
	<format align="right" size="14" bold="true" format="$#,###.00" />
	<border>
	  <edge location="top" />
	</border>
      </field>
      <field id="21" type="special" value="report.row">
	<bounds x="500" y="8" width="20" height="20" />
      </field>
      <field id="26" type="special" value="group.count">
	<bounds x="530" y="8" width="20" height="20" />
      </field>
    </section>
  </footers>

  <page>

    <!-- page headers -->
    <headers>
      <section height="30">
	<field id="3" type="text">
	  <text><![CDATA[Job #]]></text>
	  <bounds x="10" y="0" width="40" height="20" />
	  <format align="right" bold="true" underline="true" />
	</field>
	<field id="4" type="text">
	  <text><![CDATA[Title]]></text>
	  <bounds x="70" y="0" width="320" height="20" />
	  <format align="left" bold="true" underline="true" />
	</field>
	<field id="5" type="text">
	  <text><![CDATA[Hourly Rate]]></text>
	  <bounds x="400" y="0" width="100" height="20" />
	  <format align="right" bold="true" underline="true" />
	</field>
      </section>
    </headers>

    <!-- page footers -->
    <footers>
      <section height="50">
	<field id="6" type="special" value="page.number">
	  <bounds x="475" y="0" width="90" height="20" />
	  <format align="right" italic="true" format="Page 0" />
	  <border>
	    <edge location="top" number="2"/>
	  </border>
	</field>
      </section>
    </footers>

  </page>

  <!-- group -->
  <groups>
  <!-- User Columns work as group columns, even when they are not used -->
  <!-- elsewhere in the report. -->
  <group groupable-id="2" groupable-type="usercol">
    <headers>
      <section height="30">
	<field id="7" type="column" value="office.name">
	  <bounds x="0" y="0" width="250" height="20" />
	  <format align="left" size="14" bold="true" underline="true" />
	</field>
      </section>
    </headers>
    <footers>
      <section height="30">
	<field id="8" type="text">
	  <text><![CDATA[Total:]]></text>
	  <bounds x="340" y="8" width="60" height="20" />
	  <format align="right" size="14" bold="true" />
	  <border>
	    <edge location="top" />
	  </border>
	</field>
	<field id="9" type="sum" value="13"><!-- formula in field 13 -->
	  <bounds x="400" y="8" width="100" height="20" />
	  <format align="right" size="14" bold="true" format="$#,###.00" />
	  <border>
	    <edge location="top" />
	  </border>
	</field>
	<field id="22" type="special" value="report.row">
	  <bounds x="500" y="8" width="20" height="20" />
	</field>
	<field id="27" type="special" value="group.count">
	  <bounds x="520" y="8" width="20" height="20" />
	</field>
      </section>
    </footers>
  </group>
  <group column="jobs.post_date">
    <headers>
      <section height="30">
	<field id="18" type="column" value="jobs.post_date">
	  <bounds x="0" y="0" width="250" height="20" />
	  <format align="left" size="12" bold="true" underline="false" format="yyyy-MM-dd" />
	</field>
      </section>
    </headers>
    <footers>
      <section height="30">
	<field id="19" type="text">
	  <text><![CDATA[Post Date Total:]]></text>
	  <bounds x="250" y="8" width="150" height="20" />
	  <format align="right" size="14" bold="true" />
	  <border>
	    <edge location="top" />
	  </border>
	</field>
	<field id="20" type="sum" value="13"><!-- formula in field 13 -->
	  <bounds x="400" y="8" width="100" height="20" />
	  <format align="right" size="14" bold="true" format="$#,###.00" />
	  <border>
	    <edge location="top" />
	  </border>
	</field>
	<field id="23" type="special" value="report.row">
	  <bounds x="500" y="8" width="20" height="20" />
	</field>
	<field id="28" type="special" value="group.count">
	  <bounds x="520" y="8" width="20" height="20" />
	</field>
      </section>
    </footers>
  </group>
  </groups>

  <!-- details -->
  <details>
    <section height="20">
      <field id="10" type="column" value="jobs.ID">
	<bounds x="10" y="0" width="40" height="20" />
	<format align="right" />
      </field>
      <field id="11" type="column" value="jobs.title">
	<bounds x="70" y="0" width="275" height="20" />
	<!-- Set wrap to false because tests are simple and assume -->
	<!-- entire title is on one line. -->
	<format align="left" wrap="false" />
	<border>
	  <edge location="right" />
	</border>
      </field>
      <field id="12" type="column" value="jobs.hourly rate">
	<bounds x="350" y="0" width="50" height="20" />
	<format align="right" />
      </field>
      <field id="13" type="formula" value="1">
	<bounds x="400" y="0" width="100" height="20" />
	<format align="right" format="$#,###.00"/>
      </field>
      <field id="14" type="formula" value="2">
	<bounds x="500" y="0" width="75" height="20" />
	<format align="right" format="#,###.##"/>
      </field>
      <field id="24" type="special" value="report.row">
	<bounds x="510" y="8" width="20" height="20" />
      </field>
      <field id="26" type="special" value="group.count">
	<bounds x="520" y="8" width="20" height="20" />
      </field>

      <!-- We need to test a line, too -->
      <line>
	<point x="0" y="19" />
	<point x="575" y="19" />
      </line>

    </section>
  </details>

</report>

=== jarronb-iit/itms448-sourcecode-test-DataVison/jimm/datavision/test/data/eval.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- This file can read the data file charsep_data.csv -->

<!-- <!DOCTYPE report SYSTEM "report.dtd"> -->

<!-- All sizes are in points (72 points == 1 inch). -->

<!-- All coordinates and lengths are floating point, but may be truncated -->
<!-- by layout engines. -->

<!-- Colors are stored as "red;green;blue;alpha". Each component is an -->
<!-- integer from 0 to 255. -->

<!-- You will have to edit the image URL below. Search for "file:" -->

<report dtd-version="1.2"
	name="example1" title="Example Report" author="Jim Menard">

  <description><![CDATA[]]></description>

  <bean-scripting-framework default-language="Ruby">
    <language name="Ruby" class="org.jruby.javasupport.bsf.JRubyEngine"/>
  </bean-scripting-framework>

  <!-- Default orientation is portrait. -->
  <paper name="US-Letter" />

  <!-- Data source. In this case, a comma-separated file. This -->
  <!-- definition describes the file charsep_data.csv -->
  
  <source>

    <!-- The column names happen to be the same as database table.column -->
    <!-- names, but that's just a coincidence. OK, I'm lazy. -->
    <charsep sep-char=",">
      <column name="table.group" type="number" />
      <column name="table.amount" type="number" />
    </charsep>

  </source>

  <formulas>
    <formula id="1" name="header"><![CDATA[sum = 0; count = 0]]></formula>
    <formula id="2" name="detail"><![CDATA[sum += {table.amount}; count += 1]]></formula>
    <formula id="3" name="footer"><![CDATA[sum / count]]></formula>
  </formulas>

  <!-- group -->
  <groups>
  <group groupable-id="table.group" groupable-type="column">
    <headers>
      <section height="30">
      <field id="1" type="formula" value="1">
	<bounds x="8" y="8" width="16" height="16" />
      </field>
      </section>
    </headers>
    <footers>
      <section height="30">
      <field id="3" type="formula" value="3">
	<bounds x="8" y="8" width="16" height="16" />
      </field>
      </section>
    </footers>
  </group>
  </groups>

  <!-- details -->
  <details>
    <section height="20">
      <field id="100" type="column" value="table.group">
	<bounds x="0" y="0" width="40" height="20" />
      </field>
      <field id="101" type="column" value="table.amount">
	<bounds x="100" y="0" width="40" height="20" />
      </field>
      <field id="2" type="formula" value="2">
	<bounds x="200" y="0" width="40" height="20" />
      </field>
    </section>
  </details>

</report>
